---
# Variables (all with default values)
# - REDIS_VERSION
# - MEGALINTER_SERVER_VERSION
# - MEGALINTER_WORKER_VERSION
# - CODETOTAL_SERVER_IMAGE
# - CODETOTAL_SERVER_VERSION

version: '3.8'
services:
  db:
    container_name: sportsclub_db
    image: postgres
    restart: always
    ports:
      - ${PG_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data_sportsclub:/var/lib/postgresql/data
  pgadmin:
    container_name: sportsclub_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - db

volumes:
  db_data_sportsclub:
